image: Ubuntu


stack: jdk 11


branches:
  only:
    - master


build: off

install:

  - java -jar ./artifacts/app-mbank.jar &


build_script:
  - chmod +x gradlew
  - ./gradlew test --info
  - ChromeOptions options = new ChromeOptions();
    options.addArguments("--disable-dev-shm-usage");
    options.addArguments("--no-sandbox");
    options.addArguments("--headless");
    driver = new ChromeDriver(options);